version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    #mem_limit: 1024m
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - TMDB_API_KEY=${TMDB_API_KEY}
    env_file:
      - .env
    networks:
      - netflix-network
  mongo:
    image: mongo:4.4
    #container_name: mongo-container
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-data:/data/db
      #- ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - netflix-network
    restart: unless-stopped
    #command: ["mongod", "--auth", "--port", "${MONGO_PORT}"]
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: Admin1342*Server
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Admin1342*Mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: netflixclone
      ME_CONFIG_MONGODB_AUTH_SOURCE: admin
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks:
      - netflix-network
    restart: unless-stopped
volumes:
  mongo-data:

networks:
  netflix-network:
    driver: bridge