version: '3.8'

services:
  app:
    build: .
    container_name: node_backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}  # This will use the MONGO_URI from your .env file
    depends_on:
      - mongo
    networks:
      - backend_network
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["node", "backend/server.js"]