version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    #mem_limit: 1024m
    ports:
      - "4000:4000"
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - TMDB_API_KEY=${TMDB_API_KEY}
    env_file:
      - .env
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/netflix-clone --quiet
      interval: 10s
      timeout: 5s
      retries: 5
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: Admin1342Server*
    depends_on:
      - mongo
    restart: unless-stopped
volumes:
  mongo-data: